services:
- docker
script:
- docker build -t cliwrap/openjdk8-gradle-git .
# Make sure the container works normally
- docker run --rm cliwrap/openjdk8-gradle-git java -version 2>&1 | grep 'openjdk version "1.8'
# Make sure the container works normally
- docker run --rm cliwrap/openjdk8-gradle-git gradle --version 2>&1 | grep '^Gradle'
after_success:
- >
  curl -H "Content-Type: application/json"
  --data '{"source_type": "Branch", "source_name": "master"}'
  -X POST
  https://hub.docker.com/api/build/v1/source/d60be57b-6501-4ce7-b8dd-3b7a2d6644fd/trigger/54cd0bad-f510-44dc-8c0c-bce27e96f819/call/
notifications:
  email:
    recipients:
      secure: sEJC7iimQw8epg1Zszusl8O3v+XB4KBhF4QGWS12Qg/sSrWmHu8oye12pgHE1ZQpNtJ/KDLa2XKZV2Uf6kGqcutMC68NVcW1I/KkV1tuZL+ABn8U/4DDAoL4u9Y5Qj44VgIXvTAqdZc/qWO2fmIz5egMX1F2eA2Lv7LTNNqXG8Qhqq3/oAugNfYQ+hgSd+C55ejgAoxO+I76wD/h187YpymcRA4ixYYJCMRhLYD1AVg/EghjcOkAS1znEWSBynEzwOwM9sM7VL0iIYhm1Y5BiYjVvb1GqXf28T8EuYh+8GRLQaTHhgknS/17EXQC3jGvB9ayRqX5gntjeGjK/sNOsg2xIeWj38sXMbZtAdI489qSN2om1yIDuK1B6V0vUSafNl/0UN7JQTvYOCBxwrDwStR2bonaG4ScYD4lxPagtHdiD2eOr8GoBzWOLiFVYQQT7nJPLIFqW5Ev+3T2JTxHRKzE1iNW1s9EjZ8mLZTx/CA88keuFuHyywYb8ghJtlElVsd5ZzU2RdQVQHtb47BSB2ibfNo58RPzoOC/DGBmRlrjC/Vw07CeYAALA+NtYnBxxGTdZ1HjqSrSxJOfBgQM/Pt2i/5GG1rnHnfbOxaQJuJDOy1jL0ai4SO8z10TzVTsB/9t/3FpRAu7n93QsDiIr7ubeEYg0taoTuXbFVZ/Xdw=
